### ISSUE TITLE
How to deal with information for older TYPO3 versions?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Exceptions#24]
e.g. https://docs.typo3.org/typo3cms/exceptions/master/en-us/Exceptions/1375955684.html

Most of the sections (or all?) refer to older TYPO3 version. For some, the problem may still apply to newer versions. For some, it will definitely not (e.g. the top hint which refers to a security bulletin from 2013).

Should hints that only apply to older, no longer supported TYPO3 versions be removed, moved to bottom of page?

**Comment by susannemoog** [comment]
When moving the exception pages, I tried to apply the following rules: Everything older than 6.2 has been removed, in cases where the report looked old I (tried to) figured out whether it can occur in current versions and under what circumstances and added that info. 

Reordering (so that older versions are at the bottom) would probably be a good idea though. 

In general: I would not remove too much of the info, as we see at https://www.t3versions.com/statistics-detail/2 that older versions are very much still alive, and in case people need to work on these (hopefully to upgrade them), the info might still be helpful

**Comment by sypets** [comment]
Yeah, sorting that out is not so easy (even if it says 6.2. the problem might still apply etc. etc.) and I assume a lot of time and work already went into it. So if you already went through the texts (I wasn't aware of that), you probably don't want to put too much more effort into it.

All my suggestion imply - if not too much effort ...

**Comment by susannemoog** [comment]
It's totally fine - it's a good suggestion, and while I went through them once doesn't mean we shouldn't do that again - others have a lot of valuable input, too. And I admit that I might have overlooked things in the first round :) As a first step I'd say whenever you notice an issue like this, feel free to provide a PR :) 
And let's talk at the next team meeting or something about the next steps.

**Comment by cweiske** [comment]
Can this be closed? The template for the exception `.rst` file tells us to add the typo3 version and the date, can be seen on https://docs.typo3.org/typo3cms/exceptions/main/en-us/Exceptions/1561583127.html

**Comment by mbrodala** [comment]
I'd say yes, that's the scope of this ticket. Updating all existing exceptions without this info should be done separately.
